#include <iostream>
#include <string>
#include <fstream>
int main(int argc, char* argv[])
{
  using namespace std;
  string filename;
  if(int(argc) == 1)
    {
      cout << "Wellcome to Dirt Editor" << endl;
      cout << "Enter name of the file to edit: " << endl;
      cin >> filename;
    }
  else if(int(argc) == 2)
    {
      filename = argv[1];
      cout << "Editing file: " << filename << endl;
      ofstream editfile;
      editfile.open(argv[1]);
      editfile << "This text is generated by Dirt editor!" << endl;
      editfile.close();
    }
  else if(int(argc) > 2)
    {
      cout << "Please use: ./dirt [filename]" << endl;
    }
}
